# docker-compose.yml
version: '3.8'

services:
  # Nosso serviço do banco de dados PostgreSQL
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Volume para persistir os dados
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mercadorias_db
    ports:
      - "5432:5432" # Opcional: Para acessar o DB de fora com um cliente

  # Nosso serviço FastAPI
  app:
    build:
      context: ./app
    # IMPORTANTE: A aplicação agora depende do banco de dados para iniciar
    depends_on:
      - db
    environment:
      # A URL de conexão que o main.py vai usar
      - DATABASE_URL=postgresql://admin:admin@db:5432/mercadorias_db
    deploy:
      replicas: 3

  # Nosso serviço Nginx (Load Balancer)
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

# Volume para garantir que os dados do banco não se percam
volumes:
  postgres_data: