# docker-compose.yml
version: '3.8'

services:
  # Nosso serviço FastAPI
  app:
    build:
      context: ./app  # O Docker Compose vai construir a imagem a partir do Dockerfile na pasta ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 # Usando 2 workers por container
    deploy:
      replicas: 3 # << AQUI A MÁGICA ACONTECE! Estamos criando 3 instâncias da nossa API.
  
  # Nosso serviço Nginx (Load Balancer)
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"  # Mapeia a porta 80 do host para a porta 80 do container Nginx.
                 # É assim que acessamos o serviço pelo navegador.
    depends_on:
      - app      # Garante que o serviço 'app' seja iniciado antes do 'nginx'.